export const sidebarNavData = [
  {
    name: "Feed",
    icon: "newspaper",
  },
  {
    name: "Bookmarks",
    icon: "bookmarks",
  },
  {
    name: "Likes",
    icon: "heart",
  },
  {
    name: "Orders",
    icon: "cart",
  },
  {
    name: "Transactions",
    icon: "wallet",
  },
];

export const allVendors = [
  {
    id: 1,
    name: "Tolani Adeoye",
    userName: "@Chef_T",
    followersCount: 100,
    isTopRated: true,
    userImg: "./assets/food-vendors/chef-t.jpeg.png",
    accountImg: "./assets/food-vendors/food-1.jpg",
    // is the user following the vendor
    isFollowing: false,
    dateJoined: "12-04-2023",
    description: "Specialized in international cuisines",
    ratingCount: 4.5,
    reviewCount: 20,
  },
  {
    id: 2,
    name: "Funmi Adebanjo",
    userName: "@Chef_FA",
    followersCount: 100,
    isTopRated: true,
    userImg: "./assets/food-vendors/chef-funmi-adebanjo.jpg",
    accountImg: "./assets/food-vendors/funmi-catering.jpg",
    // is the user following the vendor
    isFollowing: false,
    dateJoined: "12-04-2023",
    description: "Specialized in local cuisines",
    ratingCount: 5.0,
    reviewCount: 20,
  },
  {
    id: 3,
    name: "Funmilayo Ojo",
    userName: "@chef_FO",
    followersCount: 60,
    isTopRated: true,
    userImg: "./assets/food-vendors/chef-funmi.jpg",
    accountImg: "./assets/food-vendors/chef-funmi-logo.jpg",
    // is the user following the vendor
    isFollowing: true,
    dateJoined: "12-04-2024",
    description: "Specialized in pastries",
    ratingCount: 4.0,
    reviewCount: 5,
  },
  {
    id: 4,
    name: "Hilda Baci",
    userName: "@hilda",
    followersCount: 600,
    isTopRated: true,
    userImg: "./assets/food-vendors/chef-hilda.png",
    accountImg: "./assets/food-vendors/food-2.png",
    // is the user following the vendor
    isFollowing: false,
    dateJoined: "12-04-2024",
    description: "Specialized in all dishes",
    ratingCount: 4.0,
    reviewCount: 5,
  },
  {
    id: 5,
    name: "Nelson Micheal",
    userName: "@chefCupid",
    followersCount: 80,
    isTopRated: true,
    userImg: "./assets/food-vendors/Chef_cupid.png",
    accountImg: "./assets/food-vendors/food-3.png",
    // is the user following the vendor
    isFollowing: false,
    dateJoined: "09-03-2024",
    description: "Specialized in pastries and food photography",
    ratingCount: 4.0,
    reviewCount: 56,
  },
  {
    id: 6,
    name: "Mariam Adamu",
    userName: "@chef_arewa",
    followersCount: 15,
    isTopRated: true,
    userImg: "./assets/food-vendors/Chef_arewa.png",
    accountImg: "./assets/food-vendors/food-4.png",
    // is the user following the vendor
    isFollowing: true,
    dateJoined: "05-01-2024",
    description: "Specialized in all arewa dishes",
    ratingCount: 4.0,
    reviewCount: 5,
  },
  {
    id: 7,
    name: "Gbubemi Fregene",
    userName: "@chef_fregz",
    followersCount: 1000,
    isTopRated: true,
    userImg: "./assets/food-vendors/Chef-fregz.png",
    accountImg: "./assets/food-vendors/food-5.png",
    // is the user following the vendor
    isFollowing: true,
    dateJoined: "05-01-2024",
    description: "Specialized in all French culinary",
    ratingCount: 4.8,
    reviewCount: 500,
  },
];